### PR TITLE
Add occlusion culling.

### PR DESCRIPTION
**Pull request by Syntaxxor**
I figured it'd be good to have occlusion culling built-in as an option. So I implemented it really quick. It just takes the opaque level geometry and builds an occlusion mesh off of that. It can be toggled via a boolean.

### CODE REVIEW

**Comment by jitspoe** [comment]
I haven't messed with occluders, yet, but my understanding is that you want to have very simple geometry, like a single quad to cover a whole wall, as the occluders are rendered on the CPU to check if visibility is blocked.  I don't know if using the level geometry 1:1 is a good idea, at least by default.  Could be useful to make simple occluders in trenchbroom or whatever as a separate map imported with only occlusion geometry.

**Comment by Syntaxxor** [comment]
That's fair, I haven't had enough time to measure its performance. This is based on the assumption that the geometry in your level is most likely going to be blocky, with detail being in meshes. For what I've tried, using the level geometry for occlusion produces the same results as using the built-in occlusion generation. I haven't tested with a wide range of maps, however.

**Comment by jitspoe** [comment]
Another option might be to make the occlusion culling mesh a brush entity.

I could see 3 top-level options.  Might be worth making an enum:
1) No occlusion, mesh only.
2) Render mesh + occlusion mesh (same mesh)
3) No render mesh, import as occlusion only.

Then the brush entity could be used with any of these, really.  Just slap a post_import() function on it that converts the mesh to an occlusion mesh.

**Comment by jitspoe** [comment]
Merging this as is for now -- will make a few tweaks to make it so you can specify entities as occlusion cullers, as I think that'll be more optimal.

**Pull request merged**
