### PR TITLE
Add WIP Q2 Importer

### PR DESCRIPTION
**Pull request by CSLRDoesntGameDev**
Basic Quake 2 BSP Importer, Only imports Geometry from Edges, with some work should be able to work with tris though.

### CODE REVIEW

**Comment by CSLRDoesntGameDev** [comment]
this is very broken apparently so put it on hold.......

**Comment by CSLRDoesntGameDev** [comment]
currently working on texture import and may have it done soon

**Comment by CSLRDoesntGameDev** [comment]
Texture importing is now done

**Review by jitspoe — APPROVED** [review]
CSLRDoesntGame: can your comment just be "bad code"

**Pull request merged**
